### ISSUE TITLE
Logon screen showing briefly when getting new sts token from AWS when using federated logon

### ISSUE THREAD

**Issue by mmowatt** [Noovolari/leapp#316] opened 2022-08-03 15:45 UTC
**Describe the bug**
When the STS token for AWS expires and a new one is requested.  The initial logon screen pops briefly and steals focus from the active window.  I believe this is similar to [#248] however the root cause is probably different as it only happens when the STS token session expires.

**Leapp Version**
0.13.2

**To Reproduce**
1. Create a federated profile
2. Logon with federated profile
3. Wait for STS token duration to end (default 60 minutes)
4. Logon window will appear briefly

**Expected behavior**
No window should appear and focus should not change from current working window

**Screenshots**
Unable to retrieve screenshot as the window doesn't stay up long enough

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version10.0.19044
 - Leapp Version 0.13.2

**Additional context**

**Comment by pethron** [comment] 2022-08-04 07:57
Thanks for reporting, we'll check what is causing the issue.
Do you have any way to confirm this happens on other OS as well or only on Windows?

**Comment by mmowatt** [comment] 2022-08-04 20:41
Currently I only have Windows.  I can probably setup a quick VM to test Linux.

**Comment by mmowatt** [comment] 2022-08-05 17:15
I can confirm it happens on Ubuntu Linux 22.04 as well.

**Comment by pethron** [comment] 2022-08-07 10:35
Thank you for confirming. We'll check this out.

**Comment by mmowatt** [comment] 2022-08-29 17:16
@urz9999 yes it's still happening in 0.14.2 .  We are using AzureAD as the IDP so not sure if that helps.  I will also see if I can reproduce using okta as an IDP.

**Comment by mmowatt** [comment] 2022-08-30 15:40
Here is the video

https://user-images.githubusercontent.com/25436365/187480493-a9cb7681-cbed-4c95-933b-ad0e68d316e2.mp4

**Comment by andreacavagna01** [comment] 2022-11-03 16:31
Thanks for the video. Now is clear what the problem is. 

It's for sure a problem with SAML filters, we will go deeper into investigating it!

**Comment by urz9999** [comment] 2023-01-27 15:20
Hi @mmowatt sorry for being late in responding. 

We have tried to reproduce this issue locally, however we couldn't find any evidence that our SAML filter is the culprit for this glitch. 

Probably your IdP setup makes requests to pages that are not intercepted by our filters. In order to help we are modifying the documentation, creating a section that helps developers who are trying to create/debug their own SAML filters. 
This decision, was made because most of the times, we can't reproduce the exact IdP configuration of the issuer so the best course of action is helping the developer troubleshooting the filter themselves.

Here is a proposal for the new section, so you can try by yourself. Please feel free to offer some feedback and ask for help from our community. 


**SAML authentication**

For AWS IAM Role Federated Session, Leapp prompts the user with a login page that is specific to the Identity Provider.
If the Identity token generated is not expired the login page will not be shown.

This behaviour is implemented in the [AwsIamRoleFederatedService.generateCredentials](https://github.com/Noovolari/leapp/blob/9889c32e5a8a91760789455a1faa8c82355d69e1/packages/core/src/services/session/aws/aws-iam-role-federated-service.ts#L91) method.

AwsIamRoleFederatedService.generateCredentials method verifies if the login page needs to be displayed; this check is performed through the
[AppAwsAuthenticationService.needAuthentication](https://github.com/Noovolari/leapp/blob/a50630e1f617b6332c2beb7e51fcb0cb5daa4332/packages/desktop-app/src/app/services/app-aws-authentication.service.ts#L26) method.

In particular, the needAuthentication method instantiates a headless Electron BrowserWindow that is responsible for loading the
initial IdP URL and intercepting each possible HTTP redirect call; as soon as it finds a match between a HTTP redirect call and
one of the [preset authentication URLs](https://github.com/Noovolari/leapp/blob/beadb073ea99eb71cdf56982851604172bfdba0a/packages/core/src/services/aws-saml-assertion-extraction-service.ts#L8),
it returns true, i.e. User authentication is needed. On the other hand, in case it finds a match between a HTTP redirect call and
one of the [AWS SAML assertion response URLs](https://github.com/Noovolari/leapp/blob/beadb073ea99eb71cdf56982851604172bfdba0a/packages/core/src/services/aws-saml-assertion-extraction-service.ts#L23),
it returns false, i.e. User authentication is NOT needed.

If any of the preset URLs are matched, the process timeouts after 5 seconds.

The output of the AppAwsAuthenticationService.needAuthentication method is passed to the AppAwsAuthenticationService.awsSignIn one;
awsSignIn extracts the SAML assertion from the SAML response page. The BrowserWindow object, generated by the awsSignIn method,
is shown based on the boolean output of the needAuthentication method.

The extracted SAML assertion is used to perform the AWS STS assumeRoleWithSAML API call which returns new temporary credentials.

<br>

**How to add a new SAML IdP preset authentication URL**

As described above, SAML preset authentication URL can be found in the [packages/core/src/services/aws-saml-assertion-extraction-service.ts](https://github.com/Noovolari/leapp/blob/beadb073ea99eb71cdf56982851604172bfdba0a/packages/core/src/services/aws-saml-assertion-extraction-service.ts#L8) file.
To find out what authentication URL corresponds to you specific IdP configuration, log all the intercepted HTTP redirect call inside the needAuthentication method.

```typescript
// Our request filter call the generic hook filter passing the idp response type
// to construct the ideal method to deal with the construction of the response
idpWindow.webContents.session.webRequest.onBeforeRequest((details, callback) => {

  console.log("Intercepted HTTP redirect call:", details.url);
  
  if (this.leappCoreService.authenticationService.isAuthenticationUrl(CloudProviderType.aws, details.url)) {
    clearTimeout(timeout);
    idpWindow = null;
    resolve(true);
  }
  if (this.leappCoreService.authenticationService.isSamlAssertionUrl(CloudProviderType.aws, details.url)) {
    clearTimeout(timeout);
    idpWindow = null;
    resolve(false);
  }
  // Callback is used by filter to keep traversing calls until one of the filters apply
  callback({
    requestHeaders: details.requestHeaders,
    url: details.url,
  });
});
// Start the process
idpWindow.loadURL(sanitizedField);
});
```

Execute `npm run rebuild-core-and-run-dev` to rebuild the entire solution and run the Desktop App in dev mode.

As the IdP is new to Leapp, if you start the AWS IAM Role Federated Session, it hangs; this happens because the new IdP authentication URL is not
provided in the present authentication URLs list.

To inspect the list of intercepted HTTP redirect calls, open the developer console using _Option + ⌘ + I_ (on macOS) or _Shift + CTRL + I_ 
(on Windows/Linux) combination. In the _Console_ tab, you can find the logged HTTP redirect calls; from there, discover the right
login url and map it into the [authenticationUrlRegexes](https://github.com/Noovolari/leapp/blob/beadb073ea99eb71cdf56982851604172bfdba0a/packages/core/src/services/aws-saml-assertion-extraction-service.ts#L8)
object through a valid RegEx.

We encourage you to open a Pull Request, so that we can collaborate in the implementation of the new IdP support!

**Comment by ericvilla** [comment] 2023-06-09 09:18
Hi @mmowatt! Please, let us know if you're still experiencing this problem. Thanks

**Comment by mmowatt** [comment] 2023-06-09 21:30
@ericvilla It doesn't seem to happen with our okta anymore.  It was still happening with our AzureAD, but I've not tried it in a few months. If nobody else is having the issue feel free to close this out.

**Comment by ericvilla** [comment] 2023-06-14 08:07
@mmowatt thanks for your feedback! I'm going to close the issue

**Closed by ericvilla** 2023-06-14 08:07 UTC
Labels: bug

**Comment by teddyesky** [comment] 2024-05-09 02:06
hiya - sorry to necro this issue (let me know if i should open another one), but i'm experiencing exactly the same thing with Azure AD as our federated login provider. the login window pops up for a couple seconds during token refresh and then disappears, stealing focus from whatever window is active. for reference i'm using Leapp 0.25.3 on OSX Sonoma 14.4.1

i followed the instructions above to run Leapp in dev mode and was able to retrieve the following logs. the logs during session start and during token refresh are exactly the same: (i added a couple for clarity and redacted any ID/token information):

```
app-aws-authentication.service.ts:45 Intercepted HTTP redirect call: https://myapps.microsoft.com/signin/<redacted>/<redacted>?tenantId=<redacted>
app-aws-authentication.service.ts:45 Intercepted HTTP redirect call: https://account.activedirectory.windowsazure.com/applications/signin/<redacted>/<redacted>?tenantId=<redacted>
app-aws-authentication.service.ts:45 Intercepted HTTP redirect call: https://launcher.myapps.microsoft.com/api/signin/<redacted>?tenantId=<redacted>
app-aws-authentication.service.ts:45 Intercepted HTTP redirect call: https://login.microsoftonline.com/<redacted>/oauth2/authorize?client_id=<redacted>&redirect_uri=<redacted>&response_type=code&scope=openid%20profile%20offline_access&code_challenge=<redacted>&code_challenge_method=S256&response_mode=form_post&nonce=<redacted>&client_info=1&x-client-brkrver=IDWeb.2.17.1.0&client-request-id=<redacted>&state=<redacted>&x-client-SKU=ID_NET6_0&x-client-ver=7.4.0.0
app-aws-authentication.service.ts:48 needAuthentication > Match on authentication URL: https://login.microsoftonline.com/<redacted>/oauth2/authorize?client_id=<redacted>&redirect_uri=<redacted>&response_type=code&scope=openid%20profile%20offline_access&code_challenge=<redacted>&code_challenge_method=S256&response_mode=form_post&nonce=<redacted>&client_info=1&x-client-brkrver=IDWeb.2.17.1.0&client-request-id=<redacted>&state=<redacted>&x-client-SKU=ID_NET6_0&x-client-ver=7.4.0.0
zone.js:1061 Unhandled Promise rejection: ERR_FAILED (-2) loading 'https://myapps.microsoft.com/signin/<redacted>/<redacted>?tenantId=<redacted>' ; Zone: <root> ; Task: null ; Value: Error: ERR_FAILED (-2) loading 'https://myapps.microsoft.com/signin/<redacted>/<redacted>?tenantId=<redacted>'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:77333)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:2:77708)
    at EventEmitter.emit (node:events:513:28) Error: ERR_FAILED (-2) loading 'https://myapps.microsoft.com/signin/<redacted>/<redacted>?tenantId=<redacted>'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:77333)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:2:77708)
    at EventEmitter.emit (node:events:513:28)
api.onUnhandledError @ zone.js:1061
handleUnhandledRejection @ zone.js:1086
api.microtaskDrainDone @ zone.js:1080
drainMicroTaskQueue @ zone.js:592
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
resolvePromise @ zone.js:1227
(anonymous) @ zone.js:1118
(anonymous) @ zone.js:1134
apply @ dev/scratch/leapp/packages/desktop-app/node_modules/@electron/remote/dist/src/renderer/callbacks-registry.js:54
(anonymous) @ dev/scratch/leapp/packages/desktop-app/node_modules/@electron/remote/dist/src/renderer/remote.js:353
(anonymous) @ dev/scratch/leapp/packages/desktop-app/node_modules/@electron/remote/dist/src/renderer/remote.js:335
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2
app-aws-authentication.service.ts:90 awsSignIn > Match on SAML URL: https://signin.aws.amazon.com/saml
```

from what i can tell, the URL it resolves to does end up matching the authentication URLs list. i'm not sure if the promise rejection here actually matters as it seems to end up finding the SAML url anyway. to me it seems like a quirk in the way Azure AD is handling authentication :(

right now we can work around this by using `credential-process-method` as our credential method so that this doesn't run in the background. any ideas? i'm happy to provide more debug/logs if necessary. thanks!
