### ISSUE TITLE
Malformed UTF-8 data After Mac Migration to New Macbook Pro with M1 Chip

### ISSUE THREAD

**Issue by priyankaaltman** [Noovolari/leapp#269] opened 2022-05-04 19:17 UTC
**Describe the bug**
When opening arm64 download of Leapp on new Macbook M1, I am getting a "Malformed UTF-8 data" error message and cannot interact with the application further.

**Leapp Version**
v0.12.0, also occurring on v0.11.1, v0.11.0, and v0.10.0

**To Reproduce**
I previously had a Macbook from mid 2020 (pre-M1 chip). I was using Leapp on it without issues, I believe version 0.11.0 or v0.11.1. I now have a new Macbook Pro with M1 chip.

1. I used Mac's Migration Assistant to transfer my data from the old machine to the new.
2. I downloaded the arm64 Leapp and when I open the application, I am getting a "Malformed UTF-8 data" message and cannot interact further with Leapp. I have tried v0.12.0, v0.11.1, v0.11.0, and the x64 version of v0.10.0, all with the same result.

**Expected behavior**
Leapp to open without errors.

**Screenshots**
<img width="1492" alt="Screen Shot 2022-05-04 at 12 13 16 PM" src="https://user-images.githubusercontent.com/41448668/166808978-a63d53fa-a42a-4acc-a448-dd210ce58fe3.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 12.3.1 macOS Monterey, Chip Apple M1 Pro
 - Leapp Version: v0.12.0, v0.11.1, v0.11.1, v0.10.0 

**Additional context**
I tried clearing all my aws credentials files, this did not fix. My hypothesis is something related to the migration assistant is retaining malformed cached files. Is there a way I can clear all Leapp cached files beyond deleting the application (which I have tried many times)? Thanks!

**Comment by andreacavagna01** [comment] 2022-05-05 08:08
Hi! thanks for the feedback!

At the moment the file ./Leapp/Leapp-lock.json is encrypted with the Machine ID. Since you have changed your computer, the only way to use Leapp is to delete this file and restart your configuration again, since this file cannot be decrypted anymore.

This feature will be filled in the [Pro version coming soon ](https://roadmap.leapp.cloud/c/23-import-current-configuration)with your configuration encrypted in a shared system with [zero knowledge encryption](https://docs.leapp.cloud/0.10.0/security/zero-knowledge/)

**Comment by andreacavagna01** [comment] 2022-05-05 08:09
Duplicate of #243

**Closed** 2022-05-05 08:09 UTC
Labels: documentation, duplicate

**Comment by priyankaaltman** [comment] 2022-05-09 20:45
Great, thank you for the quick response, I was able to get it working again.
