### ISSUE TITLE
Session is not started after MFA is entered

### ISSUE THREAD

**Issue by AlessandroVol23** [Noovolari/leapp#540] opened 2024-03-15 06:19 UTC
**Describe the bug**
I use Leapp with AWS SSO and multiple accounts. 
After I enter MFA I get an approved cookie request two times which I normally don't get.

And then I get this screen:
![image](https://github.com/Noovolari/leapp/assets/19362086/42b886e0-f962-4695-999f-d3f79ed0f5a4)

It doesn't close automatically. Once I close it manually no session has started.

**Leapp Version**
0.24.6

**To Reproduce**
1. Try to start the session
2. Enter username
3. Enter password
4. Enter MFA
5. Error

**Expected behavior**
Session should start. It works with other AWS Accounts. It works for other people in the same AWS Account

**Screenshots**
![image](https://github.com/Noovolari/leapp/assets/19362086/74dfb5c0-66fe-41c0-99cc-63da9049e06b)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - OS Version 14.3 (23D56)
 - Leapp Version 0.24.6

**Comment by remixtj** [comment] 2024-03-15 08:47
Hello @AlessandroVol23 we have the same issue and switched auth method from in-app to in-browser

![image](https://github.com/Noovolari/leapp/assets/1311873/d5392b2e-77e9-4d58-8334-2cf063e97c44)

**Comment by AlessandroVol23** [comment] 2024-03-15 09:00
> Hello @AlessandroVol23 we have the same issue and switched auth method from in-app to in-browser
> 
> ![image](https://private-user-images.githubusercontent.com/1311873/313124084-d5392b2e-77e9-4d58-8334-2cf063e97c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTM0MTYsIm5iZiI6MTcxMDQ5MzExNiwicGF0aCI6Ii8xMzExODczLzMxMzEyNDA4NC1kNTM5MmIyZS03N2U5LTRkNTgtODMzNC0yY2YwNjNlOTdjNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMDg1ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM0Y2M5Y2NhYjM3NDRkZTlkOGU4Njc3MTkwMjMwOWZhYTg4NGEwOGZhNjJhN2EzMTFmMTI3ZDA2YjdlYmFjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6Hm0R-bBeT1v0toNP2eIkK7C_U5_zRfUengI5bncpC4)

Thanks!
That fixes it for me as well 😊

**Comment by Anthonycyr** [comment] 2024-03-18 16:08
Same problem here this morning, the in-browser fixed it :)

**Comment by remixtj** [comment] 2024-03-18 16:23
Can you please tell in which region is your IAM Identity Center configured?
We're using eu-central-1

**Comment by Anthonycyr** [comment] 2024-03-18 16:41
of course ! Us-east-1 and ca-central-1

**Comment by iflare3g** [comment] 2024-03-19 10:33
Yeah it seems the new change introduced by AWS broke the in-app login 
I'm experiencing the same since yesterday

**Comment by sethwrowan** [comment] 2024-03-21 18:23
This appears to be related to a new UI AWS introduced for its Access Portal, which I'm guessing Leapp uses for its in-app authentication method.

**Comment by Anthonycyr** [comment] 2024-03-21 18:28
Yess, it's related for sure !

**Comment by ericvilla** [comment] 2024-03-26 16:20
We’ve just released a test build that should solve the AWS SSO in-app authentication flow.
We want to thank you for your patience and ask you to download and test the build available [here](https://github.com/Noovolari/leapp/actions/runs/8438234082).
Let us know if you have problems downloading and testing it.
Your feedback is crucial!

**Comment by remixtj** [comment] 2024-03-27 08:51
Hello,

i just tested and i keep getting cookies request and workflow doesn't continue.

Luca

**Comment by ericvilla** [comment] 2024-03-27 09:09
Yeah, I just noticed I've added support to eu-west-1 only. I'm going to release a build with support to other regions

**Comment by iflare3g** [comment] 2024-03-27 10:50
> We’ve just released a test build that should solve the AWS SSO in-app authentication flow. We want to thank you for your patience and ask you to download and test the build available [here](https://github.com/Noovolari/leapp/actions/runs/8438234082). Let us know if you have problems downloading and testing it. Your feedback is crucial!

Hello @ericvilla , I can confirm that the build works properly by using eu-west-1!
thanks a lot!!

**Comment by ericvilla** [comment] 2024-03-27 10:54
New build available: https://github.com/Noovolari/leapp/actions/runs/8449474949

**Comment by mary2501** [comment] 2024-03-29 10:24
That build doesn't work 
![image](https://github.com/Noovolari/leapp/assets/19818964/cbdfa0ad-9162-451e-98f4-2127bf1acee4)

**Comment by ericvilla** [comment] 2024-03-29 12:00
There was a problem during the v0.25.3 release process. We're going to release a fix right now

**Comment by ericvilla** [comment] 2024-03-29 13:06
Just released v0.25.3. It should fix this issue. We're going to close it. Feel free to re-open it if something goes wrong during AWS SSo in-app login

**Closed by ericvilla** 2024-03-29 13:06 UTC
Labels: bug
