### ISSUE TITLE
Unable to execute setup on windows 10

### ISSUE THREAD

**Issue by pontili** [Noovolari/leapp#31] opened 2020-10-20 09:48 UTC
![image](https://user-images.githubusercontent.com/12407596/96569422-65c3f680-12c9-11eb-9b5a-d4764d5d320e.png)

When I run execute setup on Windows 10 I have this problem.
It seems that certificates on setup file are not correct.

Thanks

**Comment by ericvilla** [comment] 2020-10-20 10:02
Hi @pontili, thank you for the bug report. 

We will investigate the cause of this bug as soon as possible. At a first glance, it seems to be related to the solution's build phase, but we need to go in-depth on this issue. Please, edit the issue template in order to add your Windows and Leapp versions.

Thank you!

**Comment by paolofulgoni** [comment] 2020-11-19 21:21
I got the same warning, except I had the option to continue anyway.
It seems from this SO answer that code signing could help: https://stackoverflow.com/questions/45250883/how-to-avoid-windows-defender-smartscreen-from-installer-when-user-download
Unfortunately I don't know how that works...
How is the setup file created?

**Comment by ericvilla** [comment] 2020-11-19 21:39
Hi @paolofulgoni, that's one of the next things we're gonna fix. It is most likely related to code signing. I think we could be able to configure code signing for the Windows build inside the package.json file. I'll provide you a complete answer as soon as I found a way to solve it. Btw, thank you for the link you provided. I'll start giving a look at that :)

**Comment by andreacavagna01** [comment] 2021-01-07 15:02
We have fixed the windows certificate, I'm going to close this issue and from the next release all the Windows version will be ok

**Closed by andreacavagna01** 2021-01-07 15:02 UTC
Labels: bug
