### ISSUE TITLE
Once build release-win get white screen, no errors

### ISSUE THREAD

**Issue by b-iurea** [Noovolari/leapp#461] opened 2023-08-18 09:08 UTC
Hi All,

after compiling the release for windows, when i execute the Leapp.exe i receive white screen and nothing else.

After I followed the steps on DEVELOPMENT.md and then tested with /build-and-run-dev/, the next step I've done are:

- ncu -u
- npm install
- npm run release-win

I'm compiling on a Ubuntu-22.04 and if i build the linux release it's work fine.
When I execute the Leapp.exe (windows executable) with wine (but also in my windows environment) I receive the white screen like the following screenshot:

![Uploading 2023-08-18 09_50_22-Cisco Secure Client.png…]()

### Details:
| Leapp Version | 0.18.5 |
| --- | --- |
| SsmPluginVersion | 1.2.339.0 |
| Platform | win32 |
| Awscli | aws-cli/2.7.12 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

**Comment by b-iurea** [comment] 2023-08-18 09:15
![2023-08-18 09_50_22-Cisco Secure Client](https://github.com/Noovolari/leapp/assets/120199048/da7b041b-3880-4e49-af2d-ec588a8b7f54)

**Comment by pethron** [comment] 2023-08-18 09:29
Hello @b-iurea , try to open the dev-tools (you can use the same shortcut as Chrome)

**Comment by b-iurea** [comment] 2023-08-18 10:36
Hi,

thank you for your answer. 

If i try to open dev-tools it anything seems to happen..

But I launched Leapp.exe from powershell with --inspect and I catch this error:

![image](https://github.com/Noovolari/leapp/assets/120199048/e3786257-92df-4cdd-b6f1-8cd366da674b)

Any suggestions?

Thank you

**Comment by pethron** [comment] 2023-08-18 10:45
Are you running multiple instances of Leapp? Maybe you didn't close the one in development?
Also, try to open the tray panel on Windows to see if you see multiple Leapp logos so you can close them (not sure how to check for that on Wine or ubuntu).

**Comment by b-iurea** [comment] 2023-08-18 11:14
You was right, the error was throwed by multiple Leapp instances opened but not visible.

Now I opened the dev-tools and seems that can't find some files.

![image](https://github.com/Noovolari/leapp/assets/120199048/3482f301-ab0f-4ed4-bbd2-56f61b14179c)

Maybe I did something wrong when i build the app.

But the steps I followed was the ones defined in development.md.

Another consideration to take, but for me is not fundamental, is that I can't Sign the executable (because no installation of CodeSignTool)
, but I don't think that is the problem, or am I wrong?

**Comment by pethron** [comment] 2023-08-18 15:18
What are you trying to achieve? Do you want to build the app, or do you want to start the local dev environment?

For starting the local dev environment I've tried to run Leapp in a fresh environment on Windows and got it to work; here are the steps I followed so I ask you to confirm you're having trouble with this process:
1. Clear all node modules in both root and packages folders
2. Be sure to use node v.16.14.0 and set it with `nvm use`
3. run `npm install` on the root (I've run it also in all packages folders to be sure)
4. run `npm run set-dev-environment` on the root
5. run `npm run clean-and-bootstrap` on the root to install packages everywhere and build the core
6. run `npm run build-and-run-dev` to start the local development of the electron app

In case of problems, you can try two quick fixes:
- In _/packages/core/_ rebuild the core package with `npm run build`
- In _/packages/desktop-app/_ rebuild keytar with `npm run rebuild-keytar`

I can't try it on Ubuntu now, but I advise against using Wine since we don't officially support it. Also on Ubuntu  you need to install `libsecret` and `gnome-keyring` before running Leapp since it relies on those to store the sensitive info, follow the docs here to install them: https://docs.leapp.cloud/latest/installation/requirements/.


The code signing works as intended since the distributed version is signed with a certificate tied to our organization.
Before building it's try to make it work in the dev environment, so let me know if this is working for you.

**Comment by b-iurea** [comment] 2023-08-18 15:51
What I'm trying to do is to build the app for windows.

The steps I've followed are this:
- git clone of repo
- nvm use in root directory
- npm install
- npm run set-dev-environment
- npm run clean-and-bootstrap
- npm run build-and-run-dev

Up to here, everything it's ok. The app work correctly. 
Consider that I work on WSL, so the local dev environment it's Ubuntu-22.04.

Once i've seen the app works correctly in local dev environment, i suppose i'm ready to release the executable.

So, the steps i followed are:
- npm run release-all (all, because I wanted to test the app both on Ubuntu (with the .deb package) and Windows with .exe.

The results on both released package are:
- Ubuntu, working as it does with .deb package and AppImage
- Windows, white screen and nothing else
- Ubuntu, trying to use Wine but same white screen as Windows environment

From my results, seems building the app was well done, but the only error I got from the building of windows release is the CodeSignTool. 
Screenshot below.
![image](https://github.com/Noovolari/leapp/assets/120199048/eddee0dc-bb7e-480b-a145-57120b02c452)

If anyone get in this problem, maybe i could try to build the app directly from windows, but since i'm a linux administrator, on powershell can be a little tricky for me.
If you could suggest me the tools and the steps to achieve this, i will be very gratefull.

Thank you for your time and answers.

**Comment by pethron** [comment] 2023-08-18 16:10
Thank you very much for the clarification. I built the app on Windows and got it to work by adding this to the _packages/desktop-app/package.json_ and running after all the preparation steps (which you should already have in place):

`"release-win-dev": "gushio gushio/target-release-dev.js \"configuration staging\" win",`

**Comment by b-iurea** [comment] 2023-08-22 10:17
Hi Pethron

also building with release-win-dev I encountered the issue.

I resolved building the app in windows environment.

So maybe the problem was WSL, maybe some missing libraries I don't know.

Thank you very much for your help, very appreciated.

**Comment by pethron** [comment] 2023-08-22 13:42
Hi @b-iurea , in the Electron docs, it says: `Don’t expect that you can build app for all platforms on one platform.`so Electron doesn't guarantee cross-platform builds, so if you need to build for Windows, you need an actual Windows machine.
I suppose WSL is interfering in some way. https://www.electron.build/multi-platform-build.html

I'll close the issue; happy to help!

**Closed by pethron** 2023-08-22 13:42 UTC
