### ISSUE TITLE
SAML authentication timeout exceeded

### ISSUE THREAD

**Issue by alper** [Noovolari/leapp#453] opened 2023-07-21 10:44 UTC
So our Leapp setup worked great up until this week when I suddenly started having this error message when trying to start a session: "SAML authentication timeout exceeded"

Some others also started to have it and it could in some cases be resolved by deleting and re-adding everything and fiddling with the settings. Not sure what the root cause is and or whether this could be fixed more fundamentally.

**Comment by Giaco9** [comment] 2023-07-21 17:55
Also in our company it is happening the same thing. Multiple versions of Leapp are involved, but it doesn't happen to all developers. We worked around it adding "&forceauthn=false" at the end of the IDP URL

**Comment by pethron** [comment] 2023-07-21 20:25
Thanks for reporting guys. I just checked (because I never had issues with the timeout exceeded issues) and indeed @urz9999, @ericvilla have and I set up our SAML IdP URL with "&forceauthn=false".

I think @Giaco9 is right or at least should work as a workaround until we find

**Comment by daveyu** [comment] 2023-07-21 20:34
We encountered this too, but actually had to change the `forceauthn` query param value from `false` to `true`. This change worked with both Google and Onelogin IdP URLs.

**Comment by unfor19** [comment] 2023-07-27 08:29
@daveyu I also changed `forceauthn` from `false to `true`, and initially it helped, but today is a new day, and I still get the same error of `SAML Authentication timeout exceeded`, were you able to resolve it for good, or do you still experience the same issue?

**Comment by aogier** [comment] 2023-07-30 17:12
Same here. Not that a "same here" is indeed very useful but I'm glad to put some more pressure on that :smiling_imp: 

now please go figure if, let's say, we decide to base our workflow on a paid plan on such a tool...

**Comment by aogier** [comment] 2023-07-31 06:55
update: erasing any local leapp data and restarting from scratch seems to solve the problem for now. This certainly puts leapp not only outside the solution, but at this point in the perimeter of the problem, but at least now it's possible to work

**Comment by unfor19** [comment] 2023-07-31 07:36
> update: erasing any local leapp data and restarting from scratch seems to solve the problem for now. This certainly puts leapp not only outside the solution, but at this point in the perimeter of the problem, but at least now it's possible to work

@aogier As an alternative, I use the Logout function rather than deleting the app
<img width="431" alt="image" src="https://github.com/Noovolari/leapp/assets/15122452/baa2017c-4d6d-467f-a5bf-914bdf9f27b1">

That means I have to insert my username + password everytime, instead of just inserting my password; Hopefully it will be fixed soon

**Comment by aogier** [comment] 2023-07-31 07:41
deleting local data != reinstalling the app. I'm happy you solved your way
tho, for me it's not viable because the long-standing, annoying #417

**Comment by pethron** [comment] 2023-07-31 08:07
We're looking into the issue and will let you know once we have news or need some info.

@aogier, why the logout couldn't work for you? It just deletes the cookie and cleans the cache.

**Comment by thinh105** [comment] 2023-07-31 08:45
Last week, I encountered this issue and temporarily resolved it by changing `&forceauthn` to true.

Everything was functioning well until I received the update prompt and decided to install the latest version.

Unfortunately, after the update, the problem persisted regardless of whether `&forceauthn` was set to true or false. The error message "SAML authentication timeout exceeded" kept appearing, and it was quite frustrating.

I made several attempts to fix the issue, such as logging out, uninstalling, reinstalling, downgrading, and upgrading, but none of these attempts worked.

After attempting to clean up the entire configuration data (https://docs.leapp.cloud/0.18.3/troubleshooting/app-data/) and then reinstalling the latest version fresh and clear, the issue was finally resolved.

**Comment by unfor19** [comment] 2023-07-31 09:22
After reading some of the code, I think the root issue is not in Leapp, as this issue is reproduced for any version of Leapp, so I think it's more of an issue with supporting something "new in AWS".

I inspected the logs of Leapp - `cat ~/Library/Logs/Leapp/log.electronService.log ` and it seems like my AWS Session Manager Plugin version is - `1 .2.312`
```
/usr/local/bin/session-manager-plugin --version
# 1 .2.312
```

I updated my [AWS Session Manager Plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/install-plugin-macos-overview.html) version to the latest version
```
/usr/local/sessionmanagerplugin/bin/session-manager-plugin --version
# 1.2.463.0
```

Did a `Logout` in Leapp, so it restarted the App, then I hit the the login again, and seems like it works; I'll report again tomorrow in case it fails.

**Comment by unfor19** [comment] 2023-07-31 10:16
After reading some of the code, I think the root issue is not in Leapp, as this issue is reproduced for any version of Leapp, so I think it's more of an issue with supporting something "new in AWS".
I inspected the logs of Leapp - `cat ~/Library/Logs/Leapp/log.electronService.log ` and it seems like my AWS Session Manager Plugin version is - `1 .2.312`
```
/usr/local/sessionmanagerplugin/bin/session-manager-plugin --version
# 1.2.312
```

I updated my [AWS Session Manager Plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/install-plugin-macos-overview.html) version to the latest version
```
/usr/local/sessionmanagerplugin/bin/session-manager-plugin --version
# 1.2.463.0
```

I did a `Logout` in Leapp, so it restarted the App; then I hit the login again, and it seems like it works; I'll report again tomorrow if it fails.

**Comment by pethron** [comment] 2023-07-31 10:42
Thanks @unfor19 for scoping it down; among the other causes, I'll check with the team if it's the Session Manager Plugin that's causing problems.

@aogier probably you're referring to the rotation flow described in https://docs.leapp.cloud/latest/security/credentials-generation/aws/ . I think adding the link on the Session primitives can clear a few doubts, in any case, we'll welcome any suggestion in making the docs more comprehensive and accessible.

**Comment by aogier** [comment] 2023-07-31 20:55
> @aogier probably you're referring to the rotation flow described in https://docs.leapp.cloud/latest/security/credentials-generation/aws/ . I think adding the link on the Session primitives can clear a few doubts, in any case, we'll welcome any suggestion in making the docs more comprehensive and accessible.

I have no idea whether the page you link has any connection with the one I linked. I wouldn't be surprised if you hadn't even looked at it, fully consistent with the lack of care I often detect in the QA of your product first of all, and secondly in dealing with the feedback you receive from those who do spend time analysing the many shortcomings of this product. Which is really a problem, considering the premise on which it is based and its aspirations.

**Comment by aogier** [comment] 2023-08-01 05:48
ok: how do you plan to investigate the issue and work on a solution?

**Comment by unfor19** [comment] 2023-08-01 06:08
> Thanks @unfor19 for scoping it down; among the other causes, I'll check with the team if it's the Session Manager Plugin that's causing problems.
> 
> @aogier probably you're referring to the rotation flow described in https://docs.leapp.cloud/latest/security/credentials-generation/aws/ . I think adding the link on the Session primitives can clear a few doubts, in any case, we'll welcome any suggestion in making the docs more comprehensive and accessible.

@pethron , sure thing, I've just checked and the error persists, so we can **rule out AWS Session Manager** as it's not related. 

Now I'm intrigued, because as I said, I'm quite sure it's something related to AWS as I've tested all versions of Leapp, and there's no way all versions "suddenly don't work", something was changed, I'm sure you guys will find it soon, thank you for your support.

In case I haven't mentioned earlier, I'm using AWS IAM Federated Login with Google SAML authentication.

**Comment by pethron** [comment] 2023-08-01 13:26
@aogier First, we are trying to replicate the bug. The possible causes could be related to the filters or the SAML authentication flow; since this error suddenly happened in multiple environments, we’re researching if there were some changes from the Google SAML authentication flow.

Moreover, we would like to organize a debugging session with @ericvilla with whoever is experiencing the bug and can lend the time; since it could be related to an Identity Provider configuration, live debugging live could be helpful.

@unfor19 We are excluding a problem with the v2/v3 version of the AWS SDK, but if you have a hunch about this, please let us know if you find anything

**Comment by aogier** [comment] 2023-08-01 13:39
it is entirely not clear to me how a bug which can be locally resolved by deleting local data and then recreating sessions could be tied to an external software but whatever, your product, your choices. Cheers

**Comment by ericvilla** [comment] 2023-08-03 09:08
Hi everyone! We tested the IAM Federated Session locally and it works fine. 

As @pethron already said, it's probably an issue related to the G Suite IdP configuration. To investigate the issue we can manage to schedule a debugging session in which, using a development build, we can find the root cause of the `SAML Authentication timeout exceeded` error. 

To determine whether the login popup should appear or not, Leapp uses a background Electron Browser Window that loads the IdP URL and, for each redirect, checks if the n-th redirect URL matches one of the `authenticationUrlRegexes` or `samlAssertionRegexes` contained in the [aws-saml-assertion-extraction-service](https://github.com/Noovolari/leapp/blob/master/packages/core/src/services/aws-saml-assertion-extraction-service.ts).
For G Suite, authentication is needed if the last redirect URL loaded matches the `/^https:\/\/accounts\.google\.com\/ServiceLogin.*/` regEx; on the other hand, if you're using AWS and no authentication is required, the last redirect URL should match the `/^https:\/\/signin\.aws\.amazon\.com\/saml/` query.

Let me describe the session rotation logic. Every 10 seconds, a background logic iterates over all the sessions; if the n-th session is active for more than 20 minutes, Leapp invokes the session-specific generateCredentials method. In case of a IAM Role Federated session that is active for more than 20 minutes, by invoking its generateCredentials method, Leapp uses the regExes that I've described before to determine if the IdP login Browser Window should appear or not. I hope it is clearer now.

As a temporary workaround, please log out from the IAM Federated Session and start that again.

In the meanwhile, we're going to build the application in dev mode, so that we can manage to debug the login flow using the dev tools. **Please, provide us the time slots that better fit your schedule, so that we can organize a debugging session.**

**Comment by ericvilla** [comment] 2023-08-03 09:39
We managed to find the root cause of the error. G Suite IdP redirects the user to the `https://accounts.google.com/AccountChooser` instead of `https://accounts.google.com/ServiceLogin*`. As far as now, we simply added a regEx that matches `https://accounts.google.com/AccountChooser` in the `authenticationUrlRegexes`. We're going to release Leapp 0.18.4 in the next hours.

**Comment by unfor19** [comment] 2023-08-07 06:38
> We managed to find the root cause of the error. G Suite IdP redirects the user to the `https://accounts.google.com/AccountChooser` instead of `https://accounts.google.com/ServiceLogin*`. As far as now, we simply added a regEx that matches `https://accounts.google.com/AccountChooser` in the `authenticationUrlRegexes`. We're going to release Leapp 0.18.4 in the next hours.

@ericvilla, thanks for the fix, I'm on macOS 2019 amd64, upgraded to version `0.18.4` and it works like a charm with `AWS IAM Role Federated`.

**Comment by pethron** [comment] 2023-08-07 07:38
Thanks for verifying. I'll close the issue; feel free to reopen it if the problem persists.

**Closed by pethron** 2023-08-07 07:38 UTC
Labels: bug
