### ISSUE TITLE
Error when login into your gsuite account

### ISSUE THREAD

**Issue by fransemino** [Noovolari/leapp#48] opened 2020-12-04 15:56 UTC
Hi, when i configure the federated login and go to the "small browser" for login into gsuite account i get error with the browser is not compatible with google.

**Comment by fransemino** [comment] 2020-12-04 16:02
![Screenshot from 2020-12-04 13-00-36](https://user-images.githubusercontent.com/47389204/101185559-c7011880-3630-11eb-844c-09d3c17f0596.png)

i dont know why is in spanish but this in english is:

**Comment by urz9999** [comment] 2020-12-04 16:09
Yes, it's rare but sometimes it can happen if you're trying to access google programmatically. Please be sure to be logged out from your normal Chrome application, close and retry. It's a random check by Google. Let me know if you manage to complete the federation setup. Also if you have already created another account and have access to the option menu, please try to log out also from it.

**Comment by fransemino** [comment] 2020-12-04 16:18
I tried but nothing. can i use chrome to login ? or only with the Leapp browser?

**Comment by ericvilla** [comment] 2020-12-04 16:20
Hi @fransemino, you cannot log in form the browser cause we need to catch the SAML response that needs to be used for assumerole-with-saml. May I ask you from where have you retrieved the SSO URL?

**Comment by fransemino** [comment] 2020-12-04 16:26
yes i'm using the same url that i was using with saml2aws : https://accounts.google.com/o/saml2/initsso?idpid=<idpid>&spid=<spid>

**Comment by ericvilla** [comment] 2020-12-04 16:31
OK, try with this template:

`https://accounts.google.com/o/saml2/initsso?idpid=my-idp-id&spid=my-dp-id&forceauthn=false`

i.e. add `&forceauthn=false` at the end of the SSO URL.

**Comment by fransemino** [comment] 2020-12-04 16:36
Eric.. the same error

**Comment by ericvilla** [comment] 2020-12-04 16:42
Ok, so that's not a problem related to the SSO URL. The thing that comes through my mind at the moment is to logout from every Google account in Chrome and clear the cache. I'm not sure of the result, but I would try that way.

**Comment by fransemino** [comment] 2020-12-04 17:19
i did that but same error

**Comment by ericvilla** [comment] 2020-12-11 15:47
Hi @fransemino, we've just released v0.3.4!

We removed the possibility to open the Developer Console, which I think was the cause of your issue.
Please, let me know if you still experience the same problem.

Thank you for your patience

**Comment by andreacavagna01** [comment] 2020-12-16 10:48
Close the Issue, because it has been solved in v0.3.4

**Closed by andreacavagna01** 2020-12-16 10:48 UTC
Labels: bug
