### ISSUE TITLE
Leapp doesn't detect AWS CLI in newer homebrew locations

### ISSUE THREAD

**Issue by jalaziz** [Noovolari/leapp#257] opened 2022-04-16 00:58 UTC
**Describe the bug**

Leapp seems to only search for the AWS CLI in `/usrl/local/bin`.

**Leapp Version**
0.11.0

**To Reproduce**
1. Obtain a new M1 Mac :)
2. Install Homebrew
3. Install AWS CLI va Homebrew (`brew install awscli`)
4. Install Leapp
5. Launch Leapp

**Expected behavior**

Leapp should detect alternative locations of the AWS CLI or allow me to configure the location. The new homebrew path is `/opt/homebrew/bin`. Although, it's probably best for Leapp to search `PATH` for the command.

**Screenshots**
<img width="416" alt="Screen Shot 2022-04-15 at 17 53 50" src="https://user-images.githubusercontent.com/247849/163655567-5655d281-6965-4b2d-8bf3-24c9c2ebeaee.png">

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Leapp 0.11.0

**Comment by joebowbeer** [comment] 2022-04-21 14:42
I just noticed this red warning with Leapp 0.11.1 - but to be clear, it is still functioning with my brew install of `aws-cli/2.4.27`

**Comment by marcusguttenplan** [comment] 2022-05-06 00:21
Hate to leave a +1, but this is also happening here.

awscli and leapp both via homebrew

<img width="445" alt="Screen Shot 2022-05-05 at 8 17 16 PM" src="https://user-images.githubusercontent.com/5815853/167047051-f780ebd8-0464-4c09-9768-ac27f7bee582.png">

**Comment by josemiguel** [comment] 2022-05-15 02:13
just create a soft link

`sudo ln -s /opt/homebrew/bin/aws /usr/local/bin/aws`

and don't forget to install the [Session Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html#install-plugin-verify) too

**Comment by nitrocode** [comment] 2022-08-08 13:58
Thanks @josemiguel. I did the following and it worked for me.

```
sudo ln -s /opt/homebrew/bin/aws /usr/local/bin/aws
sudo ln -s /opt/homebrew/bin/session-manager-plugin /usr/local/bin/session-manager-plugin
```

**Comment by nitrocode** [comment] 2022-08-08 14:06
Some digging through the code... It seems like it's trying to guess the absolute path of the binaries instead of relying on the `$PATH` of the default shell to resolve it.

https://github.com/Noovolari/leapp/blob/e11df16679792f62e9d24fc15acfdc8baacedd82/packages/desktop-app/src/app/components/tray-menu/tray-menu.component.ts#L238-L241

https://github.com/Noovolari/leapp/blob/e11df16679792f62e9d24fc15acfdc8baacedd82/packages/desktop-app/src/app/components/tray-menu/tray-menu.component.ts#L253-L256

https://github.com/Noovolari/leapp/blob/e11df16679792f62e9d24fc15acfdc8baacedd82/packages/core/src/services/execute-service.ts#L23-L43

**Comment by andreacavagna01** [comment] 2022-08-18 10:44
@urz9999  can this be added in the documentation or we can move on this issue?

**Comment by urz9999** [comment] 2022-08-18 10:55
We can try the $PATH version, but being the Electron app usually runs in a sandbox, it's not so simple. Either way, we can try a spike on the issue, and if nothing easy comes out, we can always put the suggestion in the official documentation

**Comment by joebowbeer** [comment] 2022-08-30 06:01
I noticed that the red warning now includes a link with instructions on how to create a symlink. By the way, the instructions would be clearer if they contained a typical example.

Then, after I created the link, I was surprised to see another similar-looking red warning that on closer inspection was telling me about the session-manager-plugin, even though I don't use the session-manager-plugin, and this time the link did not explain how to create a symlink.

The following worked with my brew-installed utils:

```bash
cd /usr/local/bin
ln -s $(which aws) aws
ln -s $(which session-manager-plugin) session-manager-plugin
```

**Comment by syphernl** [comment] 2022-09-15 13:46
I am seeing the same problem on my Ubuntu machine with Leapp 0.14.3.

```bash
❯ ls -alh /usr/local/bin/{aws,session-manager-plugin}
lrwxrwxrwx 1 root root 27 sep 15 15:41 /usr/local/bin/aws -> /home/frank/.asdf/shims/aws
lrwxrwxrwx 1 root root 58 feb 17  2021 /usr/local/bin/session-manager-plugin -> /usr/local/sessionmanagerplugin/bin/session-manager-plugin
```

There are symlinks and the aws cli is working fine:

```bash
❯ /usr/local/bin/aws --version
aws-cli/2.7.32 Python/3.9.11 Linux/5.15.0-47-generic exe/x86_64.ubuntu.22 prompt/off
```

Same for the `session-manager-plugin`: 

```bash
❯ /usr/local/bin/session-manager-plugin --version
1.2.54.0
```

**Comment by andreacavagna01** [comment] 2022-09-15 14:11
Thanks for the advice

**Comment by andreacavagna01** [comment] 2022-09-15 14:13
I'm going to close this issue since the problem [has been documented ](https://docs.leapp.cloud/0.14.3/troubleshooting/faq/#aws-cli-or-az-cli-is-installed-but-leapp-cant-find-it-what-can-i-do)

**Comment by kevcube** [comment] 2023-08-07 13:49
@andreacavagna01 the problem is documented but it's still annoying, Leapp works just fine without me creating the symlink, and I'd rather not do it if it isn't necessary. Can the alert be removed if `aws` is detected in `/opt/homebrew/bin` or anywhere in `$PATH`?

**Comment by kevcube** [comment] 2023-10-19 12:36
@andreacavagna01 I think this is fixed

**Comment by andreacavagna01** [comment] 2023-10-19 13:30
Thanks for pointing it out! I'm closing this issue

**Closed by andreacavagna01** 2023-10-19 13:30 UTC
Labels: bug, documentation
