### ISSUE TITLE
HTTP 429 Unknown Code

### ISSUE THREAD

**Issue by haikoschmidt** [Noovolari/leapp#308] opened 2022-07-27 13:55 UTC
**Describe the bug**
I was authorized for 2 AWS accounts with one role via AWS SSO the whole time. Now we have rolled out another role to all accounts where I am also entitled. Since then I've been getting this error message. These are authorizations for 280 additional AWS accounts.

**Leapp Version**
0.13.1 about on MacOS X

**To Reproduce**
My guess is that Leapp can't handle the number of accounts. It can certainly be reproduced if that is the case

**Expected behavior**
In Leapp I get a list of all accounts with the available roles

**Screenshots**
![Bildschirmfoto 2022-07-27 um 10 51 02](https://user-images.githubusercontent.com/56847216/181264592-fd7d7d11-63d5-4882-9fc8-cbc4475d5d28.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - OS Version 12.5
 - Leapp Version 0.13.1

**Additional context**
none

**Comment by pethron** [comment] 2022-07-27 14:12
Duplicate of #281

**Comment by pethron** [comment] 2022-08-03 08:35
Since we changed the rate with the 0.13.2 release, can you please confirm the error is gone?

**Comment by pethron** [comment] 2022-08-05 09:47
Closing, since we had no other reports after 0.13.2 release. Feel free to reopen #281 .

**Closed by pethron** 2022-08-05 09:47 UTC
Labels: bug
