### ISSUE TITLE
Failed at the zlib@1.0.5 preinstall script 'node-waf clean || true; node-waf configure build'.

### ISSUE THREAD

**Issue by eswidler** [Noovolari/leapp#539] opened 2024-03-11 22:29 UTC
**Describe the bug**
When installing the Leapp CLI, an error occurs related to using `node-waf`

**Leapp Version**
Leapp CLI 0.1.64

**To Reproduce**
1. Node: `21.7.1`
2. NPM: `10.5.0`
3. Run `brew install Noovolari/brew/leapp-cli`
4. Experience error:
```
npm ERR! command failed
npm ERR! command sh -c node-waf clean || true; node-waf configure build
npm ERR! sh: node-waf: command not found
npm ERR! sh: node-waf: command not found
npm verb exit 127
```

**Expected behavior**
The Leapp CLI should be installed

**Screenshots**
![Screenshot 2024-03-11 at 12 29 24 PM (1)](https://github.com/Noovolari/leapp/assets/1088478/ed0a3f61-316b-4cec-a7b2-fad2f27ae3cf)

**Desktop (please complete the following information):**
 - OS: Mac
 - OS Version 14.3.1
 - Leapp CLI 0.1.64

**Comment by ms-ati** [comment] 2024-03-13 16:10
Any idea of a timeline for this? Am I the only person in the world who cannot install Leapp CLI until this is resolved?

**Comment by ericvilla** [comment] 2024-03-15 11:01
Hi @ms-ati, that's an issue related to the node-zlib library, which is deprecated. I'm gonna try to replace the deprecated packages with the Node.js built-in one

**Comment by ericvilla** [comment] 2024-03-15 12:05
CLI v0.1.65 is out! Please, try that new version and let me know if the problem is solved. If so, I'm going to release the desktop app, so that the new version is notified to all the users automatically

**Comment by ms-ati** [comment] 2024-03-15 21:53
Thanks and apologies - how do I try this? I’ve been installing on Mac OS using Homebrew?

**Comment by ms-ati** [comment] 2024-03-25 14:05
@ericvilla Thank you so much! I can confirm that version v0.1.65 installed successfully using `brew install Noovolari/brew/leapp-cli` -- all set!

**Comment by ericvilla** [comment] 2024-03-26 15:06
Great to hear that it is working @ms-ati! I'm going to close the issue

**Closed by ericvilla** 2024-03-26 15:06 UTC
Labels: bug
