### ISSUE TITLE
AWS Session Expiration Issue

### ISSUE THREAD

**Issue by BPCS-wit** [Noovolari/leapp#220] opened 2022-02-01 09:41 UTC
When using SSO to AWS over browser a session is created which is only to last 8 hours (setup within AWS). But the leapp app assuming 7 days. After 8 hours (when switching profiles) an invalid token message appears.
Only way to solve is to go to Integrations->Logout -> then Login again

**Leapp Version**
0.8.1.0

**Expected behavior**
Reopen the browser SSO dialog to refresh the token

**Screenshots**
![image](https://user-images.githubusercontent.com/58041976/151945749-d568cb49-2a65-4175-88b2-bc41d616cdc7.png)

**Desktop (please complete the following information):**
 - Windows 10 (x64)

**Comment by pethron** [comment] 2022-02-01 09:44
Can this be linked to #108 ?
@ericvilla @andreacavagna01

**Comment by BPCS-wit** [comment] 2022-02-01 09:47
@pethron yes it can. Actually the issue appeared last week for me after updating from 0.8.0 to 0.8.1 therefore I thought the issue is new.

**Comment by ericvilla** [comment] 2022-02-01 09:48
@pethron @BPCS-wit I'll check it out! Thank you for reporting

**Comment by tgjohnst** [comment] 2022-02-08 19:58
I have also been encountering this issue, thanks for flagging the issue and temporary workaround. Looking forward to a fix.

**Comment by Jay1305** [comment] 2022-02-09 01:48
First of all thank you very much to all developers for creating such wonderful tool and idea 💯.

With my case, I upgraded today from 0.7.3 to 0.8.1 on my mac. All profiles showed up but none of them were connecting. When opened integrations menu, it was showing 3 days and online opposed to 8 hours. So tried to log off and then logged back in as temporary workaround. It started showing 8 hours and online.

![image](https://user-images.githubusercontent.com/31636584/153103727-68c6c027-7e49-43ca-97d1-c2b8ac6cde80.png)

But when was trying to activate any session, it was showing error with Region.

![image](https://user-images.githubusercontent.com/31636584/153103059-aebd7c63-6951-4249-9a08-df5a0290051c.png)

Tried multiple attempts but it is now not allowing me to activate any session. I had followed up [this](https://github.com/Noovolari/leapp/issues/108) and current 220 issue very recently, like couple of days before. I deleted all entries from keychain. After logout it shows "Cleaning configuration file" and then restarts but still not able to login. But I am not able to now open any session at all. Not sure if I should create different issue as this is mixture of both.

**Comment by andreacavagna01** [comment] 2022-02-09 09:24
@Jay1305 Thank you so much for the appreciation to the project! At least you can try to delete the `~/.Leapp/Leapp-lock.json` file. This will erase your current configuration and you will start with a brand new configuration, this will make the app works. 
We are still troubleshooting this issue even for the next version

**Comment by Jay1305** [comment] 2022-02-12 01:19
Hey @andreacavagna01! Thanks for your reply. I had tried literally everything (deleted leapp-lock, removed from keychain, 
 restarted mac, and so on mentioned in [this](https://github.com/Noovolari/leapp/issues/108#issuecomment-1026657174) comment, but from that day leapp is not working at all when I upgraded from 0.7.3 to 0.8.2. So finally decided to download the dev code to at least find what the issue is with my local environment. I am not js developer so can you please tell me what I can find more here? 

It is getting failed here -
![image](https://user-images.githubusercontent.com/31636584/153690360-b38afb13-07ac-4fde-8b1e-ca3ba1ae1ade.png)

Console
![image](https://user-images.githubusercontent.com/31636584/153690329-acffc6b5-5c32-4f5e-8837-29aede814d27.png)

Thanks again :)

**Comment by zswanson** [comment] 2022-02-15 14:46
This may have been something on the AWS side - we'd been seeing this with 0.8.1 for at least 2 weeks and then its suddenly stopped and the integration options no longer show that 7 day expiration period.

**Comment by andreacavagna01** [comment] 2022-02-15 14:48
Absolutely. We save the expiration code time directly from AWS SSO OIDC sdk. But the token is valid only for 8 hours

**Comment by ericvilla** [comment] 2022-02-15 22:21
I can confirm it. The aws-sdk/clients/ssooidc's createToken method returned a token valid for 7 days (no Leapp overhead). We tried to force a previous version of the AWS SDK, but it still wasn't working. Now it seems to work as expected, returning a token valid for 8 hours.

**Comment by BPCS-wit** [comment] 2022-02-18 08:43
So, the behavior changed for me. Now I am getting 8 hours (as expected) for session duration. After the 8 hours a new token is generated. For me, the app is now working as expected.
Maybe an issue on the AWS site?

**Comment by ericvilla** [comment] 2022-02-19 15:04
Yes @BPCS-wit, it was not related to Leapp itself but to the AWS SSO createToken API response. I'm going to close the issue

**Closed by ericvilla** 2022-02-19 15:04 UTC
Labels: bug
