### ISSUE TITLE
Maintain IAM Role Chained Configurations based on SSO Assumer session

### ISSUE THREAD

**Issue by cornevandersteen** [Noovolari/leapp#209] opened 2021-12-29 11:36 UTC
**Is your feature request related to a problem? Please describe.**
We use SSO for our AWS organization (MSP), within this SSO organization we created AWS accounts as "service accounts".
These service accounts are directly synced via the SSO integration with Leapp. 

The service accounts have a trust with our customers own AWS-accounts via a Cross Account Sign-in role. We use the IAM Role Chained setup with an assumer session from one of our AWS Service Accounts.

Each time the SSO session is expired or synced, the configured sessions via the IAM Role Chained - assumer session are removed.
Probably due to a link between these chained session configuration and the sso 

**Describe the solution you'd like**
Don't remove the IAM Role Chained based on SSO accounts

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by pethron** [comment] 2022-01-19 09:21
Thanks for reporting @cornevandersteen , we've actually fixed this bug but it's not yet released! I'll leave it open until the new release come out.

**Comment by andreacavagna01** [comment] 2022-01-31 11:24
With the latest release the problem is solved

**Comment by FrankFioretti** [comment] 2022-04-29 18:14
Has there been any movement on this? I am having this issue as well.

**Comment by andreacavagna01** [comment] 2022-11-03 15:04
This is solved now with v.0.16.0. I can close the issue now, feel free to re-open the issue if the problem persists

**Closed by andreacavagna01** 2022-11-03 15:04 UTC
Labels: bug
