### ISSUE TITLE
0.11 with okta keeps popping up the logging window every few seconds

### ISSUE THREAD

**Issue by innovia** [Noovolari/leapp#255] opened 2022-04-13 18:24 UTC
**Describe the bug**
every few seconds the login for okta would popup and immediately goes away

**Leapp Version**
0.11

**To Reproduce**
1.connect to one of the profiles
2. wait a minute or two and the window will pop up and close continuously every few seconds

**Expected behavior**
should not show that screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version [e.g. 22]
 - Leapp Version [e.g. 0.2.5]

**Additional context**

**Comment by pethron** [comment] 2022-04-13 18:56
Duplicate of #248

We already fixed on master if you want to try out, or wait for the next release.

**Comment by innovia** [comment] 2022-04-19 17:38
thanks i'll give it a try!

**Comment by ericvilla** [comment] 2022-04-21 11:12
Solved in [v0.11.1](https://www.leapp.cloud/releases) release. I'm going to close it

**Closed by ericvilla** 2022-04-21 11:12 UTC
Labels: bug
