### ISSUE TITLE
SSO setup does not allow pasting URL

### ISSUE THREAD

**Issue by zswanson** [Noovolari/leapp#156] opened 2021-08-13 11:16 UTC
**Describe the bug**
When setting up AWS SSO, Leapp does not allow progressing with login if the url was pasted into the sign on url entry field. Instead it keeps presenting the error text that I must enter the url. Only works if I fully delete the pasted text and then input manually. 

**Leapp Version**
0.6.2

**To Reproduce**
1. Go to integrations and set up a new AWS SSO
2. Copy/paste an aws sso url into the url field - observe error text
3. Press login 
4. Delete the url, retype by hand
5. press login

**Expected behavior**
The interface should allow paste behavior and recognize that the field has been populated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 11.4
 - Leapp Version: 0.6.2

**Comment by pethron** [comment] 2021-08-16 13:55
Thanks for reporting but I wasn't able to reproduce the issue.
Can you expand a bit on the steps? Did you previously have a correct integration setup?

**Comment by jgrumboe** [comment] 2021-08-19 10:12
I'm also not able to reproduce it.

**Comment by pethron** [comment] 2021-08-20 15:24
I'll close this issue, feel free to reopen if this problem arises again.

**Closed by pethron** 2021-08-20 15:24 UTC
Labels: bug
