### ISSUE TITLE
Profile page have "undiefined" proxy URL

### ISSUE THREAD

**Issue by agatim** [Noovolari/leapp#20] opened 2020-10-05 09:51 UTC
**Describe the bug**
In the profile section, if no proxy URL is provided, the textbox contains "undefined" string.

**Screenshots**
![Screenshot 2020-10-05 at 11 49 54](https://user-images.githubusercontent.com/14805455/95065206-01b60580-0701-11eb-9258-cb57f6b5364e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.7

**Comment by ericvilla** [comment] 2020-10-05 09:53
Thank @agatim for the bug report. We are currently working on the feature that allows you to set up a Web Proxy to send HTTP requests to.

**Comment by pethron** [comment] 2020-10-05 09:55
This is already being taken care in #8 
If you have suggestion move discussion to that issue

**Comment by pethron** [comment] 2020-10-05 09:56
Duplicate of #8

**Closed by pethron** 2020-10-05 09:56 UTC
Labels: bug
