### ISSUE TITLE
AWS SSO asks to confirm device code but Leapp doesn't give one

### ISSUE THREAD

**Issue by imaginaryCorn** [Noovolari/leapp#470] opened 2023-09-14 21:07 UTC
**Describe the bug**
A code confirmation comes up in the AWS SSO devices auth where one didn't exist before. The code to confirm doesn't appear in the Leapp UI.

**Leapp Version**
0.20.0

**To Reproduce**
1. Login to AWS Single Sign-on through Leapp
2. The browser or in-app page opens to `https://device.sso.*.amazonaws.com/?user_code=xxx` and asks to confirm user code given to you.
3. Leapp gives the user no code to check against.

**Expected behavior**
Leapp should show the code in its UI that comes from the call to the AWS SSO API, so users can visually confirm which device is requesting SSO access.

**Screenshots**
(code whited out)
![image (5)](https://github.com/Noovolari/leapp/assets/17042068/fc135691-1516-4a4d-8091-7aa99b35235f)

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version Ventura 13.5.2
 - Leapp Version 0.20.0

**Comment by nilsdebruin** [comment] 2023-09-15 08:44
I can confirm that this is also the case in version 0.19.0 (same confirmation code pop-up)

**Desktop (please complete the following information):**

* OS: MacOS
* OS Version Ventura 13.5.2
* Leapp Version 0.19.0

**Comment by pethron** [comment] 2023-09-15 08:53
Thank you guys for reporting. We'll look into this.

**Comment by pethron** [comment] 2023-09-15 10:22
Are you guys still able to use SSO even without seeing the code?

**Comment by siipimutteri** [comment] 2023-09-15 11:04
It's still usable. Just need to press "Confirm and continue" without ability to check the code and then more familiar "Authorisation request" with just Accept and Cancel is shown.

**Comment by pethron** [comment] 2023-09-18 08:19
Hi guys, I couldn't reproduce this issue on 0.20.0 in-app and in-browser.
It's strange it's happening to you because we don't manipulate the pages sent by AWS or other providers. Can you confirm you're still experiencing the issue?

**Comment by nilsdebruin** [comment] 2023-09-18 09:06
@pethron Yes, I am still experiencing this (also our team members, versions 0.19.0 and 0.20.0 Mac)!

**Comment by pethron** [comment] 2023-09-18 09:58
I'm confused about the issue, so I'll rephrase it so we can proceed.

Can you confirm that when you do the authentication flow, you see the code in leapp? Be it in-browser or in-app (like the screenshot below), and does it change with each new request? 
![image](https://github.com/Noovolari/leapp/assets/12462586/b50a3049-09d9-4e6c-bf76-ec8e7d06b0de)

The main point of the issue is that you don't find the code displayed outside of Leapp to compare with the one shown. Is that correct?


I expected AWS to send an email, an SMS, or something similar, but this code appears nowhere. I'm investigating this feature since I need to understand if AWS devised this to let the client send an email, SMS, or any other channel to transmit the code or if there's an API to call to send this code somehow.

This could be a problem for Leapp since to send the code, it would need an email, SMS, or, in general, an external service to send the code.

**Comment by mattzcarey** [comment] 2023-09-18 10:16
> I'm confused about the issue, so I'll rephrase it so we can proceed.
> 
> Can you confirm that when you do the authentication flow, you see the code in leapp? Be it in-browser or in-app (like the screenshot below), and does it change with each new request? ![image](https://user-images.githubusercontent.com/12462586/268608854-b50a3049-09d9-4e6c-bf76-ec8e7d06b0de.png)
> 
> The main point of the issue is that you don't find the code displayed outside of Leapp to compare with the one shown. Is that correct?
> 
> I expected AWS to send an email, an SMS, or something similar, but this code appears nowhere. I'm investigating this feature since I need to understand if AWS devised this to let the client send an email, SMS, or any other channel to transmit the code or if there's an API to call to send this code somehow.
> 
> This could be a problem for Leapp since to send the code, it would need an email, SMS, or, in general, an external service to send the code. Alternatively, we could display the code inside Leapp without sending it.

We are getting this also. I would suggest displaying the code inside Leapp would be best. :)

Also @pethron can you settle a debate for us?

Is Leapp pronounced le-app or lee-ap?

Best,
Matt

**Comment by pethron** [comment] 2023-09-18 10:20
Thanks everyone for the clarification. We'll find a way to display the code before redirecting to the portal.

Quoting the docs :) 
> The name Leapp is based on the word leap and is pronounced /l:ip/. We chose this name because the project enables you to be one step away from your cloud environments.

**Comment by pethron** [comment] 2023-09-19 15:33
We found a way to show the code inside Leapp before sending the request. It will be available in the next release.

![image](https://github.com/Noovolari/leapp/assets/12462586/a5ec36eb-9b62-4282-b0c8-800d3a845054)

**Comment by andreacavagna01** [comment] 2023-09-21 10:22
Since no action is required, I think the message displaying is meaningless.

Should we think to change the wording?

**Comment by pethron** [comment] 2023-09-21 16:06
Closing issue as fixed with version [0.20.1](https://github.com/Noovolari/leapp/compare/v0.20.0...v0.20.1).

![image](https://github.com/Noovolari/leapp/assets/12462586/c4d6eb8a-5338-458c-aa8f-599077f725d9)
![image](https://github.com/Noovolari/leapp/assets/12462586/8628d1ae-4a65-4304-9b62-4ebb23d7cf67)

**Closed by pethron** 2023-09-21 16:06 UTC
Labels: bug
