### ISSUE TITLE
AWS Plain account creds always put under "default" profile in credentials file

### ISSUE THREAD

**Issue by rezaetezal** [Noovolari/leapp#107] opened 2021-04-15 16:46 UTC
## Description
**Plain** AWS account credentials created under the `[default]` profile in `~/.aws/credentials` file and not the named profile as configured in the application. This does not seem to affect **SSO** credentials.

## Steps to Reproduce
1. Create two AWS profiles from Options menu in Leapp: `prod` and `dev`
2. Create **Plain** AWS account from main Leapp window and set its profile to `prod`
3. Create **SSO** AWS account from main Leapp window and set its profile to `dev`
4. Activate both account from main Leapp window
5. Open the `~/.aws/credentials` file and observe that two profiles exist: `dev` and `default`

## Expected behavior
Two profiles exist in `~/.aws/credentials`: `dev` and `prod`

## Actual behavior
Two profiles exist in `~/.aws/credentials`: `dev` and `default`

## Environment
 - OS: MacOS Catalina
 - OS Version: 10.15.7
 - Leapp Version: 0.4.7

**Comment by andreacavagna01** [comment] 2021-04-15 18:00
Will look at it tomorrow, thanks for reporting

**Comment by urz9999** [comment] 2021-04-16 07:15
already on this one, stay tuned

**Comment by urz9999** [comment] 2021-04-16 07:29
ok, found the cause, working on it

**Comment by andreacavagna01** [comment] 2021-04-22 08:54
Fixed released in v0.5.0, now the token is saved correctly and changed whenever the profile change.

Closing the issue

**Closed by andreacavagna01** 2021-04-22 08:54 UTC
Labels: bug
