### ISSUE TITLE
Unable to access the aws cli commands for multiple aws accounts using leapp. 

### ISSUE THREAD

**Issue by AditModi** [Noovolari/leapp#119] opened 2021-05-24 09:48 UTC
I have just started out using leapp and this may be due to lack of understanding on my part.
I have installed leapp setup on my windows system.
I have configured multiple aws account ( plain ) using the leapp app console.
I have activated particular aws account.

problems I am facing:
when I try to ran the aws cli commands ( eg. aws s3 ls ) , I am unable to get the s3 buckets for my specific aws account.

As I understand , there seems to be an issue with my system. 
can you please help me understand what mistakes I am making and how to correct them? 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version [e.g. 10]
 - Leapp Version [e.g. 0.5.3]

**Comment by andreacavagna01** [comment] 2021-05-24 09:52
Hi, please join our slack community if you need some online troubleshooting of what is not working, the issue provided is too generic to have a concise answer.

Have you look into the logs if something is giving you errors in the starting Session process?

this is the link to the community:
https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q

**Comment by andreacavagna01** [comment] 2021-05-24 12:23
closing this issue because the problem is solved

**Closed by andreacavagna01** 2021-05-24 12:23 UTC
Labels: bug
